version: "3.8"

services:
  angular-app:
    build: .
    container_name: angular11-app
    working_dir: /app
    volumes:
      - ./mi-app-angular:/app
    ports:
      - "4200:4200"
    command: ng serve --host 0.0.0.0 --poll 2000